runtime: nodejs14
handlers:
  - url: /((.*\/)*[^\/]+\.[^\/]+)$
    static_files: build/\1
    upload: build/.*

  - url: .*
    static_files: build/index.html
    upload: build/index.html
env_variables:
  API_URL: "https://gcp-backend-7aeqgkv7xa-ey.a.run.app"

env: standard
instance_class: F2
automatic_scaling:
  min_instances: 3
  max_instances: 40
  target_cpu_utilization: 0.6
